### ISSUE TITLE
Add automation for lifecycling stale issues

### ISSUE THREAD

**Issue by asmacdo** [java-operator-sdk/java-operator-sdk#481]
A bot to mark issues stale and close long-stale issues could help to keep the issue tracker from exploding too much.

**Comment by asmacdo** [comment]
Operator-SDK is using https://github.com/apps/openshift-ci/installations/new, and could be an option for us as well

**Comment by sclorng** [comment]
You may use a github action https://github.com/actions/stale

eg:

```
name: 'Close stale issues and PRs'
on:
  workflow_dispatch:
  schedule:
  - cron: '30 1 * * *'

jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/stale@v4.1.0
      with:
        days-before-issue-stale: 30
        days-before-pr-stale: 45
        days-before-issue-close: 5
        days-before-pr-close: 10
        stale-issue-message: >
          This issue is stale because it has been open 30 days with no activity.
          Remove stale label or comment or this will be closed in 5 days.
        close-issue-message: >
          This issue was closed because it has been stalled for 5 days with no activity.
        stale-pr-message: >
          This PR is stale because it has been open 45 days with no activity.
          Remove stale label or comment or this will be closed in 10 days.
        close-pr-message: >
          This PR was closed because it has been stalled for 10 days with no activity.
        stale-issue-label: 'stale'
        exempt-issue-labels: 'needs-discussion,help wanted,never stale'
        stale-pr-label: 'stale'
        exempt-pr-labels: 'never stale'
        operations-per-run: 500
        ascending: true
```
